spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            client-secret: ${KAKAO_SECRET}
            authorization-grant-type: authorization_code            # yml은 특수문자 사용 시 쌍따옴표를 사용해야함.
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"       # {baseUrl}을 사용하면 현재 스프링 도메인으로 치환해준다.
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # 인가코드
            token-uri: https://kauth.kakao.com/oauth/token              # 토큰
            user-info-uri: https://kapi.kakao.com/v2/user/me            # 유저 정보
            user-name-attribute: id                                     # 응답 중 유저를 식별할 수 있는 식별자 정보
    jwt:
      secret: ${JWT_SECRET}
      expired_time:
        access_token: ${ACCESS_TOKEN_EXPIRED_TIME_MS}
        refresh_token: ${REFRESH_TOKEN_EXPIRED_TIME_MS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          timeout: 5000
          starttls:
            enable: true
          auth: false
  profiles:
    active: prod



