spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

client:
  url: http://localhost:5173

logging:
  level:
    org.springframework.security: trace
    com.project.com.project.study: trace
    org.hibernate.type.descriptor.sql.BasicBinder: debug
